module.exports = [
  {
    id: 1,
    name: 'Aloe_Vera___Healthy',
    plantId: 1,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none']
  },
  {
    id: 2,
    name: 'Aloe_Vera___Rot',
    plantId: 1,
    symptoms: [
      'dark brown, mushy root tips and dark, mushy lower leaves',
      'leaves turn mushy and collapse',
      'The spots may enlarge and merge together',
    ],
    causalAgent: ['Phytophthora', 'Pythium'],
    envFactors: ['Overwatering', 'poor drainage'],
    mitigation: ['Remove and replant new pups', 'Cut back on watering'],
  },
  {
    id: 3,
    name: 'Aloe_Vera___Rust',
    plantId: 1,
    symptoms: ['black or brown circular spots on the leaves'],
    causalAgent: ['none'],
    envFactors: ['Too much water on leaves'],
    mitigation: [
      'Spray a solution of one teaspoon of baking soda in one quart of water',
    ],
  },
  {
    id: 4,
    name: 'Apple___Apple_scab',
    plantId: 2,
    symptoms: [
      'Scabby spots are sunken and tan and may have velvety spores in the center',
      'As these spots mature, they become larger and turn brown and corky',
      'Infected fruit becomes distorted and may crack allowing entry of secondary organisms',
      'Severely affected fruit may drop, especially when young.',
    ],
    causalAgent: ['Venturia inaequalis'],
    envFactors: ['none'],
    mitigation: [
      'Choose resistant varieties when possible.',
      'Water in the evening or early morning hours (avoid overhead irrigation) to give the leaves time to dry out before infection can occur.',
      'Spread a 3- to 6-inch layer of compost under trees',
    ],
  },
  {
    id: 5,
    name: 'Apple___Black_rot',
    plantId: 2,
    symptoms: [
      'reddish brown cankers slightly below the level of the healthy bark around it.',
      'spread more quickly along the length of the branch',
    ],
    causalAgent: ['Botryosphaeria'],
    envFactors: ['Temperature'],
    mitigation: [
      'Remove the cankers by pruning at least 15 inches below the end and burn or bury them',
    ],
  },
  {
    id: 6,
    name: 'Apple___Cedar_apple_rust',
    plantId: 2,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 7,
    name: 'Apple___healthy',
    plantId: 2,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 8,
    name: 'Blueberry___healthy',
    plantId: 3,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 9,
    name: 'Cassava___Bacterial_Blight',
    plantId: 4,
    symptoms: [
      'blight, wilting, dieback, and vascular necrosis',
      'angular necrotic spotting of the leaves',
      'spots begin as distinguishable moist, brown lesions normally restricted to the bottom of the plant until they enlarge and coalesce',
      'pools of gum exudate along wounds and leaf cross veins',
      ' It begins as a sappy golden liquid and hardens to form an amber colored deposit',
    ],
    causalAgent: ['Xanthomonas axonopodis'],
    envFactors: ['none'],
    mitigation: ['Pruning or total extirpation of infected plant tissue'],
  },
  {
    id: 10,
    name: 'Cassava___Brown_Steak',
    plantId: 4,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 11,
    name: 'Cassava___Green_Mite',
    plantId: 4,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 12,
    name: 'Cassava___Mosaic_Virus',
    plantId: 4,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 13,
    name: 'Cherry___Powdery_mildew',
    plantId: 5,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 14,
    name: 'Cherry___healthy',
    plantId: 5,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 15,
    name: 'Corn___Common_rust',
    plantId: 6,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 16,
    name: 'Corn___Gray_leaf_spot',
    plantId: 6,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 17,
    name: 'Corn___Northern_Leaf_Blight',
    plantId: 6,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 18,
    name: 'Corn___healthy',
    plantId: 6,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 19,
    name: 'Date_Palm___Brown_Spots',
    plantId: 7,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 20,
    name: 'Date_Palm___Healthy',
    plantId: 7,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 21,
    name: 'Grape___Black_rot',
    plantId: 8,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 22,
    name: 'Grape___Esca_(Black_Measles)',
    plantId: 8,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 23,
    name: 'Grape___Leaf_blight',
    plantId: 8,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 24,
    name: 'Grape___healthy',
    plantId: 8,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 25,
    name: 'Orange___Citrus_greening',
    plantId: 9,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 26,
    name: 'Peach___Bacterial_spot',
    plantId: 10,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 27,
    name: 'Peach___healthy',
    plantId: 10,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 28,
    name: 'Pepper_bell___Bacterial_spot',
    plantId: 11,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 29,
    name: 'Pepper_bell___healthy',
    plantId: 11,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 30,
    name: 'Potato___Early_blight',
    plantId: 12,
    symptoms: [
      'The spots of this disease on the leaves are brown to black with concentric rings.',
      'These spots are in numerous numbers and are scattered all over the leaves.',
      'Heavily infested leaves fall off after drying.',
      'Spots also appear on stems.',
    ],
    causalAgent: ['Alternaria solani'],
    envFactors: ['none'],
    mitigation: [
      'Plant disease-free seed ',
      'Maintain good soil fertility and crop vigor ',
      'Harvest when skin is mature to avoid bruising and in turn infection of tubers',
    ],
  },
  {
    id: 31,
    name: 'Potato___Late_blight',
    plantId: 12,
    symptoms: [
      'Sporangia develop on the leaves',
      'dark blotches on leaf tips and plant stems',
      'White mold will appear under the leaves in humid conditions',
      'Infected tubers develop grey or dark patches that are reddish brown beneath the skin',
    ],
    causalAgent: ['Phytophthora infestans'],
    envFactors: ['none'],
    mitigation: ['piling soil or mulch around the stems'],
  },
  {
    id: 32,
    name: 'Potato___healthy',
    plantId: 12,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 33,
    name: 'Raspberry___healthy',
    plantId: 13,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 34,
    name: 'Rice___Bacterial_leaf_blight',
    plantId: 14,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 35,
    name: 'Rice___Brown_spot',
    plantId: 14,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 36,
    name: 'Rice___Healthy',
    plantId: 14,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 37,
    name: 'Rice___Leaf_smut',
    plantId: 14,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 38,
    name: 'Soybean___healthy',
    plantId: 15,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 39,
    name: 'Squash___Powdery_mildew',
    plantId: 16,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 40,
    name: 'Strawberry___Leaf_scorch',
    plantId: 17,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 41,
    name: 'Strawberry___healthy',
    plantId: 17,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 42,
    name: 'Tomato___Bacterial_spot',
    plantId: 18,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 43,
    name: 'Tomato___Early_blight',
    plantId: 18,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 44,
    name: 'Tomato___Late_blight',
    plantId: 18,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 45,
    name: 'Tomato___Leaf_Mold',
    plantId: 18,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 46,
    name: 'Tomato___Septoria_leaf_spot',
    plantId: 18,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 47,
    name: 'Tomato___Spider_mites',
    plantId: 18,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 48,
    name: 'Tomato___Target_Spot',
    plantId: 18,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 49,
    name: 'Tomato___Yellow_Leaf_Curl_Virus',
    plantId: 18,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 50,
    name: 'Tomato___healthy',
    plantId: 18,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
  {
    id: 51,
    name: 'Tomato___mosaic_virus',
    plantId: 18,
    symptoms: ['none'],
    causalAgent: ['none'],
    envFactors: ['none'],
    mitigation: ['none'],
  },
];
