module.exports = [
  {
    id: 1,
    name: 'BIO T PLUS',
    solutionFor: 4,
    uploadedBy: 1,
    solutionTypeId: 1,
    applicationRate: '50g/100Lt',
    whoClassId: 4,
    whoSignalId: 2,
  },
  {
    id: 2,
    name: 'CLODIGAN 240 EC',
    solutionFor: 6,
    uploadedBy: 5,
    solutionTypeId: 1,
    applicationRate: '0.4-0.6l/Ha',
    whoClassId: 3,
    whoSignalId: 2,
  },
  {
    id: 3,
    name: 'DOMARK 40 EW',
    solutionFor: 15,
    uploadedBy: 1,
    solutionTypeId: 1,
    applicationRate: '0.6Lt/Ha',
    whoClassId: 2,
    whoSignalId: 1,
  },
  {
    id: 4,
    name: 'RAPID 120 SC',
    solutionFor: 30,
    uploadedBy: 1,
    solutionTypeId: 1,
    applicationRate: '0.25 – 0.4 L/Ha',
    whoClassId: 3,
    whoSignalId: 2,
  },
  {
    id: 5,
    name: 'SHAR COMBI 280SC',
    solutionFor: 11,
    uploadedBy: 5,
    solutionTypeId: 1,
    applicationRate: '0.75L/Ha',
    whoClassId: 3,
    whoSignalId: 2,
  },
  {
    id: 6,
    name: 'FENOMEN 400 EC',
    solutionFor: 4,
    uploadedBy: 5,
    solutionTypeId: 1,
    applicationRate: '20-24Lt/Ha',
    whoClassId: 1,
    whoSignalId: 3,
  },
  {
    id: 7,
    name: 'ARDENT 50 SC ',
    solutionFor: 5,
    uploadedBy: 1,
    solutionTypeId: 1,
    applicationRate: '50ml/100Lt',
    whoClassId: 2,
    whoSignalId: 1,
  },
  {
    id: 8,
    name: 'Honeycrisp ',
    uploadedBy: 1,
    solutionFor: 4,
    solutionTypeId: 2,
    applicationRate: '',
    whoClassId: null,
    whoSignalId: null,
  },
  {
    id: 9,
    name: 'Akane',
    uploadedBy: 5,
    solutionFor: 4,
    solutionTypeId: 2,
    applicationRate: '',
    whoClassId: null,
    whoSignalId: null,
  },
  {
    id: 10,
    name: 'NAT-31',
    uploadedBy: 1,
    solutionFor: 11,
    solutionTypeId: 2,
    applicationRate: '',
    whoClassId: null,
    whoSignalId: null,
  },
  {
    id: 11,
    name: 'ECU-72',
    uploadedBy: 5,
    solutionFor: 11,
    solutionTypeId: 2,
    applicationRate: '',
    whoClassId: null,
    whoSignalId: null,
  },
  {
    id: 12,
    name: 'aRRestor',
    uploadedBy: 5,
    solutionFor: 15,
    solutionTypeId: 2,
    applicationRate: '',
    whoClassId: null,
    whoSignalId: null,
  },
  {
    id: 13,
    name: 'Excellency',
    uploadedBy: 1,
    solutionFor: 15,
    solutionTypeId: 2,
    applicationRate: '',
    whoClassId: null,
    whoSignalId: null,
  },
  {
    id: 14,
    name: 'Prevailer',
    uploadedBy: 1,
    solutionFor: 15,
    solutionTypeId: 2,
    applicationRate: '',
    whoClassId: null,
    whoSignalId: null,
  },
];
